language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov selenium
env:
  - DJANGO_SETTINGS_MODULE=camera_imagefield.tests.settings DJANGO_ALLOWED_HOSTS=localhost
script: PYTHONPATH=. coverage run --source=. `which django-admin.py` test
after_success:
  - codecov
